/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as ForbiddenRouteImport } from './routes/forbidden'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AppWarehousesIndexRouteImport } from './routes/_app/warehouses/index'
import { Route as AppSuppliersIndexRouteImport } from './routes/_app/suppliers/index'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppPurchaseOrdersIndexRouteImport } from './routes/_app/purchase-orders/index'
import { Route as AppProfileIndexRouteImport } from './routes/_app/profile/index'
import { Route as AppProductsIndexRouteImport } from './routes/_app/products/index'
import { Route as AppCategoriesIndexRouteImport } from './routes/_app/categories/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppPurchaseOrdersNewRouteImport } from './routes/_app/purchase-orders/new'
import { Route as AppProductsNewRouteImport } from './routes/_app/products/new'
import { Route as AppPurchaseOrdersPoIdIndexRouteImport } from './routes/_app/purchase-orders/$poId/index'
import { Route as AppProductsProductIdIndexRouteImport } from './routes/_app/products/$productId/index'
import { Route as AppProductsProductIdEditRouteImport } from './routes/_app/products/$productId/edit'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppWarehousesIndexRoute = AppWarehousesIndexRouteImport.update({
  id: '/warehouses/',
  path: '/warehouses/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSuppliersIndexRoute = AppSuppliersIndexRouteImport.update({
  id: '/suppliers/',
  path: '/suppliers/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPurchaseOrdersIndexRoute = AppPurchaseOrdersIndexRouteImport.update({
  id: '/purchase-orders/',
  path: '/purchase-orders/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProfileIndexRoute = AppProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProductsIndexRoute = AppProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCategoriesIndexRoute = AppCategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPurchaseOrdersNewRoute = AppPurchaseOrdersNewRouteImport.update({
  id: '/purchase-orders/new',
  path: '/purchase-orders/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProductsNewRoute = AppProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPurchaseOrdersPoIdIndexRoute =
  AppPurchaseOrdersPoIdIndexRouteImport.update({
    id: '/purchase-orders/$poId/',
    path: '/purchase-orders/$poId/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppProductsProductIdIndexRoute =
  AppProductsProductIdIndexRouteImport.update({
    id: '/products/$productId/',
    path: '/products/$productId/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppProductsProductIdEditRoute =
  AppProductsProductIdEditRouteImport.update({
    id: '/products/$productId/edit',
    path: '/products/$productId/edit',
    getParentRoute: () => AppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/forbidden': typeof ForbiddenRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/products/new': typeof AppProductsNewRoute
  '/purchase-orders/new': typeof AppPurchaseOrdersNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/categories/': typeof AppCategoriesIndexRoute
  '/products/': typeof AppProductsIndexRoute
  '/profile/': typeof AppProfileIndexRoute
  '/purchase-orders/': typeof AppPurchaseOrdersIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/suppliers/': typeof AppSuppliersIndexRoute
  '/warehouses/': typeof AppWarehousesIndexRoute
  '/products/$productId/edit': typeof AppProductsProductIdEditRoute
  '/products/$productId/': typeof AppProductsProductIdIndexRoute
  '/purchase-orders/$poId/': typeof AppPurchaseOrdersPoIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/forbidden': typeof ForbiddenRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/products/new': typeof AppProductsNewRoute
  '/purchase-orders/new': typeof AppPurchaseOrdersNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/categories': typeof AppCategoriesIndexRoute
  '/products': typeof AppProductsIndexRoute
  '/profile': typeof AppProfileIndexRoute
  '/purchase-orders': typeof AppPurchaseOrdersIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/suppliers': typeof AppSuppliersIndexRoute
  '/warehouses': typeof AppWarehousesIndexRoute
  '/products/$productId/edit': typeof AppProductsProductIdEditRoute
  '/products/$productId': typeof AppProductsProductIdIndexRoute
  '/purchase-orders/$poId': typeof AppPurchaseOrdersPoIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_auth': typeof AuthRouteRouteWithChildren
  '/forbidden': typeof ForbiddenRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_app/': typeof AppIndexRoute
  '/_app/products/new': typeof AppProductsNewRoute
  '/_app/purchase-orders/new': typeof AppPurchaseOrdersNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/categories/': typeof AppCategoriesIndexRoute
  '/_app/products/': typeof AppProductsIndexRoute
  '/_app/profile/': typeof AppProfileIndexRoute
  '/_app/purchase-orders/': typeof AppPurchaseOrdersIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/suppliers/': typeof AppSuppliersIndexRoute
  '/_app/warehouses/': typeof AppWarehousesIndexRoute
  '/_app/products/$productId/edit': typeof AppProductsProductIdEditRoute
  '/_app/products/$productId/': typeof AppProductsProductIdIndexRoute
  '/_app/purchase-orders/$poId/': typeof AppPurchaseOrdersPoIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forbidden'
    | '/unauthorized'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/products/new'
    | '/purchase-orders/new'
    | '/api/auth/$'
    | '/categories/'
    | '/products/'
    | '/profile/'
    | '/purchase-orders/'
    | '/settings/'
    | '/suppliers/'
    | '/warehouses/'
    | '/products/$productId/edit'
    | '/products/$productId/'
    | '/purchase-orders/$poId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forbidden'
    | '/unauthorized'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/products/new'
    | '/purchase-orders/new'
    | '/api/auth/$'
    | '/categories'
    | '/products'
    | '/profile'
    | '/purchase-orders'
    | '/settings'
    | '/suppliers'
    | '/warehouses'
    | '/products/$productId/edit'
    | '/products/$productId'
    | '/purchase-orders/$poId'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/forbidden'
    | '/unauthorized'
    | '/_auth/forgot-password'
    | '/_auth/reset-password'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_app/'
    | '/_app/products/new'
    | '/_app/purchase-orders/new'
    | '/api/auth/$'
    | '/_app/categories/'
    | '/_app/products/'
    | '/_app/profile/'
    | '/_app/purchase-orders/'
    | '/_app/settings/'
    | '/_app/suppliers/'
    | '/_app/warehouses/'
    | '/_app/products/$productId/edit'
    | '/_app/products/$productId/'
    | '/_app/purchase-orders/$poId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ForbiddenRoute: typeof ForbiddenRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_app/warehouses/': {
      id: '/_app/warehouses/'
      path: '/warehouses'
      fullPath: '/warehouses/'
      preLoaderRoute: typeof AppWarehousesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/suppliers/': {
      id: '/_app/suppliers/'
      path: '/suppliers'
      fullPath: '/suppliers/'
      preLoaderRoute: typeof AppSuppliersIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/purchase-orders/': {
      id: '/_app/purchase-orders/'
      path: '/purchase-orders'
      fullPath: '/purchase-orders/'
      preLoaderRoute: typeof AppPurchaseOrdersIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/profile/': {
      id: '/_app/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AppProfileIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/products/': {
      id: '/_app/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AppProductsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/categories/': {
      id: '/_app/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof AppCategoriesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/purchase-orders/new': {
      id: '/_app/purchase-orders/new'
      path: '/purchase-orders/new'
      fullPath: '/purchase-orders/new'
      preLoaderRoute: typeof AppPurchaseOrdersNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/products/new': {
      id: '/_app/products/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof AppProductsNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/purchase-orders/$poId/': {
      id: '/_app/purchase-orders/$poId/'
      path: '/purchase-orders/$poId'
      fullPath: '/purchase-orders/$poId/'
      preLoaderRoute: typeof AppPurchaseOrdersPoIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/products/$productId/': {
      id: '/_app/products/$productId/'
      path: '/products/$productId'
      fullPath: '/products/$productId/'
      preLoaderRoute: typeof AppProductsProductIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/products/$productId/edit': {
      id: '/_app/products/$productId/edit'
      path: '/products/$productId/edit'
      fullPath: '/products/$productId/edit'
      preLoaderRoute: typeof AppProductsProductIdEditRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppProductsNewRoute: typeof AppProductsNewRoute
  AppPurchaseOrdersNewRoute: typeof AppPurchaseOrdersNewRoute
  AppCategoriesIndexRoute: typeof AppCategoriesIndexRoute
  AppProductsIndexRoute: typeof AppProductsIndexRoute
  AppProfileIndexRoute: typeof AppProfileIndexRoute
  AppPurchaseOrdersIndexRoute: typeof AppPurchaseOrdersIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppSuppliersIndexRoute: typeof AppSuppliersIndexRoute
  AppWarehousesIndexRoute: typeof AppWarehousesIndexRoute
  AppProductsProductIdEditRoute: typeof AppProductsProductIdEditRoute
  AppProductsProductIdIndexRoute: typeof AppProductsProductIdIndexRoute
  AppPurchaseOrdersPoIdIndexRoute: typeof AppPurchaseOrdersPoIdIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppProductsNewRoute: AppProductsNewRoute,
  AppPurchaseOrdersNewRoute: AppPurchaseOrdersNewRoute,
  AppCategoriesIndexRoute: AppCategoriesIndexRoute,
  AppProductsIndexRoute: AppProductsIndexRoute,
  AppProfileIndexRoute: AppProfileIndexRoute,
  AppPurchaseOrdersIndexRoute: AppPurchaseOrdersIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppSuppliersIndexRoute: AppSuppliersIndexRoute,
  AppWarehousesIndexRoute: AppWarehousesIndexRoute,
  AppProductsProductIdEditRoute: AppProductsProductIdEditRoute,
  AppProductsProductIdIndexRoute: AppProductsProductIdIndexRoute,
  AppPurchaseOrdersPoIdIndexRoute: AppPurchaseOrdersPoIdIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ForbiddenRoute: ForbiddenRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
